
#define PACKAGE_NAME    "QjackCtl"
#define PACKAGE_VERSION "0.3.1.4"

#define CONFIG_PREFIX   "."
#define CONFIG_DEBUG    1

#define CONFIG_SYSTEM_TRAY

#define CONFIG_JACK_TRANSPORT
#define CONFIG_JACK_REALTIME
#define CONFIG_JACK_STATISTICS
#define CONFIG_JACK_XRUN_DELAY
#define CONFIG_JACK_MAX_DELAY

#undef  CONFIG_JACK_MIDI
#undef  CONFIG_ALSA_SEQ

#undef  CONFIG_ROUND
